// Scans the git-ignored extensions folder (`apps/app/extensions/<id>/`) and
// writes the two registries the app imports as `@extensions/server` and
// `@extensions/client`. Both are git-ignored; tsconfig `paths` fall back to the
// checked-in `*.empty.ts` before this has run.
//
// Each `<id>/` folder is one extension (the folder name is its id) holding:
//   server.ts    default-exports a ServerExtension   (server registry)
//   client.tsx   default-exports a ClientExtension   ("use client"; client
//                registry)
// An extension that needs its own dependencies adds a package.json and becomes
// a workspace package (pnpm-workspace.yaml globs this folder); the registries
// still import it by relative path.
//
// Plain Node, no TS: next.config.mjs imports it before the TS pipeline exists.
// It writes only when the content changes, so `next dev` doesn't loop on its
// own output.

import {
  existsSync,
  readdirSync,
  readFileSync,
  watch,
  writeFileSync,
} from "node:fs"
import { dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))

/** The extensions folder: inside the app, so imports resolve its dependencies. */
export const EXTENSIONS_DIR = join(here, "..", "..", "extensions")

const ID = /^[a-z0-9][a-z0-9-]*$/

const REGISTRIES = [
  {
    name: "server",
    files: ["server.ts", "server.tsx"],
    header: [
      'import "server-only"',
      "",
      'import type { ServerExtension } from "@/lib/extensions/types"',
    ],
    exportName: "serverExtensions",
    type: "ServerExtension",
  },
  {
    name: "client",
    files: ["client.tsx", "client.ts"],
    header: ['import type { ClientExtension } from "@/lib/extensions/types"'],
    exportName: "clientExtensions",
    type: "ClientExtension",
  },
]

/** The extension folders, sorted by id. Throws on a folder it can't use. */
export function listExtensions(dir = EXTENSIONS_DIR) {
  if (!existsSync(dir)) return []
  const found = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue
    const path = join(dir, entry.name)
    if (!ID.test(entry.name)) {
      throw new Error(
        `[extensions] ${path}: a folder name is the extension's id, so use lowercase letters, digits and dashes`
      )
    }
    const files = Object.fromEntries(
      REGISTRIES.map((r) => [
        r.name,
        r.files.find((f) => existsSync(join(path, f))),
      ])
    )
    if (!files.server && !files.client) {
      throw new Error(
        `[extensions] ${path} has no server.ts or client.tsx, so it adds nothing`
      )
    }
    found.push({ id: entry.name, path, files })
  }
  return found.sort((a, b) => a.id.localeCompare(b.id))
}

/** The source of one registry module for the given extensions. */
export function registrySource(registry, extensions, outDir) {
  const r = REGISTRIES.find((x) => x.name === registry)
  const imports = []
  const entries = []
  extensions.forEach(({ id, path, files }, n) => {
    const file = files[registry]
    if (!file) return
    let spec = relative(outDir, join(path, file)).replace(/\\/g, "/")
    spec = spec.replace(/\.tsx?$/, "")
    if (!spec.startsWith(".")) spec = `./${spec}`
    imports.push(`import ext${n} from ${JSON.stringify(spec)}`)
    entries.push(`  ${JSON.stringify(id)}: ext${n},`)
  })
  return [
    "// GENERATED by lib/extensions/codegen.mjs from apps/app/extensions/.",
    "// Do not edit; git-ignored.",
    ...r.header,
    ...imports,
    "",
    `export const ${r.exportName}: Record<string, ${r.type}> = {`,
    ...entries,
    "}",
    "",
  ].join("\n")
}

function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false
  writeFileSync(path, content)
  return true
}

/**
 * Write `server.generated.ts` and `client.generated.ts` next to this file.
 * @param {{ dir?: string, outDir?: string, log?: boolean }} [opts]
 * @returns {{ extensions: string[] }}
 */
export function generateExtensionRegistry(opts = {}) {
  const outDir = opts.outDir ?? here
  const extensions = listExtensions(opts.dir ?? EXTENSIONS_DIR)
  const ids = extensions.map((e) => e.id)
  let changed = false
  for (const { name } of REGISTRIES) {
    const source = registrySource(name, extensions, outDir)
    changed =
      writeIfChanged(join(outDir, `${name}.generated.ts`), source) || changed
  }
  if (changed && opts.log !== false) {
    console.log(
      `[extensions] registries written: ${ids.join(", ") || "no extensions"}`
    )
  }
  return { extensions: ids }
}

let watching = false

/**
 * `next dev` only: regenerate when an extension folder or its server/client
 * file is added or removed, so a new extension shows up without a restart.
 * Edits inside an extension need nothing: Turbopack already watches them.
 * Debounced; the write is a no-op when nothing changed.
 */
export function watchExtensions() {
  if (watching) return
  watching = true
  let timer
  const regenerate = () => {
    clearTimeout(timer)
    timer = setTimeout(() => {
      try {
        generateExtensionRegistry()
      } catch (err) {
        console.error(String(err instanceof Error ? err.message : err))
      }
    }, 200)
  }
  try {
    watch(dirname(EXTENSIONS_DIR), (_e, name) => {
      if (name === "extensions") regenerate()
    }).unref()
    if (existsSync(EXTENSIONS_DIR)) {
      watch(EXTENSIONS_DIR, { recursive: true }, (_e, name) => {
        if (name && !name.includes("node_modules")) regenerate()
      }).unref()
    }
  } catch (err) {
    console.warn(`[extensions] not watching ${EXTENSIONS_DIR}: ${err}`)
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  generateExtensionRegistry()
}
