window.FINDINGS = [
{id:"V1",sev:"high",title:"Screenshots are stretched to the column, so the UI shows at three sizes and details are soft",
where:"Every guide page with screenshots (about 20 detail images: home-search, canvas-menu, route-picker, recreate-dialog, composer-skills…)",
what:"Every image is stretched to the 832px column whatever its capture size. Full-window shots show app text at 0.55× (a 14px label reads as 7.7px); detail crops show it at 1.5× (21px, bigger than body text), so the recreate dialog's title outsizes the page's own 27px H1. Details are 1344px natural at 832px, a 1.62× ratio, so they are visibly soft on a retina screen. On Workspaces the same Workspaces menu appears at two scales 30px apart.",
fix:"<code>components/screenshot.tsx</code>: add <code>srcSet=\"… 2x\"</code> to both images. Captures are 2x, so each renders at its own size, capped at the column, and details show the UI at about 1.2×, sharp.",
applied:true, shots:["scale"]},
{id:"V2",sev:"high",title:"Detail crops slice neighbouring UI and bury the subject",
where:"building/knobs, building/skills, play-mode (play-hud, play-device-menu), home (home-canvas-menu, home-folder-menu), canvas-menu, quickstart (setup-gate), repositories (project-settings, add-project-menu)",
what:"The harness grows every crop to a 560×360 minimum around its focus, so small subjects get padded with cut-off neighbours: the knobs shot slices the demo headline and 'Book a demo' and ends in 75px of empty canvas; the skills shot has 210px of sliced pricing page; play-hud puts the control bar in 4% of the frame; the Device menu is clipped at its top edge; the setup card has 315px above it and 120px below. In dark mode these crops are 84% white, a glaring slab on the black page. Two form shots also captured the magenta focus ring, and tall dialogs are shrunk by the 36rem cap until helper text is about 9px.",
fix:"<code>apps/app/screenshots/docs/frame.ts</code> and <code>screens.ts</code>: per-screen minimum size for menu, HUD and popover focuses so the crop hugs the focus plus padding; measure play-device-menu from the open menu's full box; recentre setup-gate (<code>[360,197,560,392]</code>); blur the active element before capture; crop dialogs to the dialog. The after shots here are hand crops of the existing captures to show the target, not harness output.",
applied:"mockup", shots:["crop-knobs","crop-skills","crop-hud","crop-setup"]},
{id:"V3",sev:"high",title:"The frosted navbar smears the text scrolling under it",
where:"Every page, once scrolled; strongest in light mode",
what:"Nextra's navbar is 70% page colour with a backdrop blur, so whatever scrolls beneath it shows as a grey ghost band behind the logo and search. The app's own headers are solid.",
fix:"<code>app/globals.css</code>: <code>.nextra-navbar-blur</code> gets the solid page colour and no backdrop filter.",
applied:true, shots:["navbar"]},
{id:"V4",sev:"high",title:"A stray blank line splits a Quickstart paragraph at the N key",
where:"quickstart, step 2 'Create a canvas'",
what:"'…on the home screen (or' ends one paragraph and 'N) creates and opens another one' starts the next, with a full paragraph gap between them.",
fix:"<code>content/quickstart.mdx</code>: delete the empty line before <code>&lt;kbd&gt;N&lt;/kbd&gt;</code>.",
applied:true, shots:["qs-split"]},
{id:"V5",sev:"medium",title:"Italics are slanted by the browser, and headings get a slanted display face",
where:"Every *emphasis* (quickstart, agent, repositories table, blockquote); headings 'GitHub (desktop)', 'Coding agents (desktop)', 'Comments (hosted)'",
what:"Only upright Instrument Sans is loaded, so every italic is a synthesized slant of the upright font (bold 'CLI' crowds the next word). Unbounded has no italic at all, so '(desktop)' in an H2 reads like a rendering bug.",
fix:"<code>app/layout.tsx</code>: load Instrument Sans with <code>style: [\"normal\", \"italic\"]</code>. <code>globals.css</code>: emphasis inside headings becomes a quiet upright aside in the text face at 0.85em, 60% opacity.",
applied:true, shots:["italic","italic-zoom"]},
{id:"V6",sev:"medium",title:"Table columns wrap short labels and jump between stacked tables",
where:"environment-variables (8 tables), keyboard-shortcuts (6 tables), deploying-to-vercel, frames, play-mode, terminals, self-hosting, model-providers",
what:"Auto layout sizes every table on its own: on Environment variables the Variable column is 257, 213, 312, 175, 153, 183, 305 and 228px wide, so the Description edge moves as you scroll; the six shortcut tables start their Action column at six different x positions. Short first-column labels wrap ('Back, / Forward', 'Record / flow', '← Back to / canvas', 'OpenAI- / compatible') while the other column has room.",
fix:"<code>mdx-components.tsx</code> tags each table with its header labels (<code>data-head</code>). <code>globals.css</code>: first-column labels don't wrap; tables headed 'Variable|…' get a fixed 32% first column (15% for Required) and 'Shortcut|Action' a fixed 30%, so every table of one shape lines up.",
applied:true, shots:["tables-env","kbd-tables","tables-wrap"]},
{id:"V7",sev:"medium",title:"Code chips break mid-token with sliced edges",
where:"20 chips on 11 pages: skills (screenplay-share-state), development (packages/screenplay-state), byo-harnesses, dev-server URL, database, screenshots, ADR paths in callouts",
what:"Chips wrap inside the token ('screenplay-share- / state', 'http://my- / branch…'), and <code>box-decoration-break: slice</code> leaves each half with one square, unpadded edge.",
fix:"<code>globals.css</code>: chips in tables never wrap; chips in prose use <code>box-decoration-break: clone</code> so both halves keep their padding and corners.",
applied:true, shots:["code-wrap"]},
{id:"V8",sev:"medium",title:"Code blocks have the one darker hairline on the page",
where:"All 43 code blocks, on 15 pages",
what:"Nextra rings code blocks in gray-300 (#d4d4d4) in light and neutral-700 (#404040) in dark. Cards, tables, callouts, the search box and Copy page all use the app's border (black 12%, white 16%), so code blocks read heavier than everything around them.",
fix:"<code>globals.css</code>: set <code>--tw-ring-color</code> on <code>article pre</code> to the border token in each theme.",
applied:true, shots:["code-ring"]},
{id:"V9",sev:"medium",title:"'On this page' marks the current heading in magenta",
where:"Every page's table of contents",
what:"The sidebar's current page is a neutral fill with medium-weight foreground text (Zack's call in #1109), but the TOC's current heading is still Nextra's primary magenta, so the two navs disagree.",
fix:"<code>globals.css</code>: the active TOC link is foreground and medium weight (with the 98.8% stretch, so it doesn't shift width).",
applied:true, shots:["toc"]},
{id:"V10",sev:"medium",title:"Previous and next links are 18px, the biggest text in the chrome",
where:"Bottom of every page",
what:"Nextra sets the pagination links to 18px medium with 20px chevrons, larger than the 16px body and the 14px sidebar they point into.",
fix:"<code>globals.css</code>: 14px medium, 16px chevrons.",
applied:true, shots:["pagination"]},
{id:"V11",sev:"medium",title:"The 404 page is Next's unstyled default",
where:"Any missing docs URL",
what:"A system-font '404 | This page could not be found.' with a grey divider, unlike anything else on the site.",
fix:"New <code>app/not-found.tsx</code> using Nextra's <code>NotFoundPage</code>, with the title in Unbounded at the 27px page-title size and a 'Report this broken link' link.",
applied:true, shots:["notfound"]},
{id:"V12",sev:"medium",title:"Code in a heading grows the heading and squashes the mono text",
where:"byo-harnesses, 'Hosted: SANDBOX_HARNESSES'",
what:"The chip inherits 0.9em of the 20px heading (18px) and the heading's −0.6px tracking. The H2 box grows from 25px to 31.7px and the chip nearly touches the rule below.",
fix:"<code>globals.css</code>: code in H2/H3 is 0.8em with normal tracking and no vertical padding.",
applied:true, shots:["h2-code"]},
{id:"V13",sev:"medium",title:"The env file is highlighted as shell, and comment columns drift",
where:"environment-variables Quick start, desktop-app desktop.env, screenshots 'The three commands'",
what:"The env block is fenced as bash, so <code>&lt;openssl rand -hex 32&gt;</code> parses as redirects (magenta &lt; &gt;, blue 'rand' and '32') and only some values are coloured. Trailing comments sit at different columns within one block (7 columns apart in desktop.env; the fourth screenshots command 4 columns off).",
fix:"Fence the env file as <code>dotenv</code>; re-pad each block to one comment column.",
applied:true, shots:["env-block","comments"]},
{id:"V14",sev:"medium",title:"Two screenshots stacked with nothing between them read as one broken image",
where:"home (search results, then folder), frames (route picker, then workspace picker)",
what:"Each pair is separated only by the 28px figure margin. On Frames both show the same chart and address bar, so they look like one image with a seam.",
fix:"A one-line caption under each (the existing <code>caption</code> prop). With V1 the pair also drops to its real size.",
applied:true, shots:["stacked"]},
{id:"V15",sev:"medium",title:"Steps end with a 48px gap",
where:"github-oauth, self-hosting, deploying-to-vercel",
what:"<code>.nextra-steps</code> has a 48px bottom margin, so the paragraph after step 3 sits 48px down where paragraphs are 20px apart, and a following H2 sits 48px down where it is 40px everywhere else.",
fix:"<code>globals.css</code>: steps end on the 1.25em paragraph margin.",
applied:true, shots:["steps-gap"]},
{id:"V16",sev:"medium",title:"External links underline a trailing space, and the arrow can wrap alone",
where:"External links on 22 pages; the orphaned arrow on desktop-app",
what:"Nextra renders <code>text&amp;nbsp;↗</code> inside the underlined link, so the underline runs under the space and stops short of the arrow. On desktop-app '#404' ends a line and its ↗ wraps to the next one.",
fix:"<code>mdx-components.tsx</code>: an <code>a</code> override glues the last word and the arrow in a no-wrap span and puts the gap in a margin instead of an underlined space.",
applied:true, shots:["extlink"]},
{id:"V17",sev:"low",title:"Callout text is grey, not the foreground",
where:"22 callouts",
what:"The article text rule skips callouts, so their body is Nextra's gray-800 in light and gray-200 in dark while the paragraphs around them are black and white.",
fix:"<code>globals.css</code>: callout body in the foreground.",
applied:true, shots:["callout"]},
{id:"V18",sev:"low",title:"Sidebar section labels float halfway between groups",
where:"Sidebar and mobile menu",
what:"Each label has an 8px bottom margin on top of its 6px padding, so it sits as far from its own first item as from the group above.",
fix:"<code>globals.css</code>: no bottom margin, so the label reads as its group's heading.",
applied:true, shots:["sidebar"]},
{id:"V19",sev:"low",title:"Diagrams don't sit on the screenshot rhythm, and two have cramped details",
where:"concepts, self-hosting, screenshots",
what:"Diagrams are 672px and left-aligned, so on Core concepts the diagram's right edge stops 160px short of the screenshot below it, and they use a 24px/0 margin where screenshots use 28px. The architecture diagram's sandbox chips have 2.5px side padding ('coding CLIs'). The screenshots diagram puts 'gitignored' hugging its box while the other notes align at one column, and sets the last note in mono.",
fix:"<code>diagram.module.css</code>: centre the SVG and use the screenshot margin. <code>diagrams.tsx</code>: widen the service column (160 to 184) so every chip is 80px; one note column and the sans note style in the screenshots diagram.",
applied:true, shots:["diagram-width","arch-diagram","shots-diagram"]},
{id:"V20",sev:"low",title:"The skill YAML example overflows its code block",
where:"building/skills",
what:"The <code>description:</code> line clips at 'new endp' (889px of content in 832px) with no fade.",
fix:"Fold the example description with <code>&gt;-</code> over two lines.",
applied:true, shots:["yaml"]},
{id:"V21",sev:"low",title:"File tree rows change pitch after a nested folder",
where:"building/skills, development",
what:"A folder's children are 24px apart but siblings after a nested group are 28px apart, so 'SKILL.md → release-notes' breaks the rhythm.",
fix:"<code>globals.css</code>: one 4px gap at every level.",
applied:true, shots:["filetree"]},
{id:"V22",sev:"low",title:"'Run command …' shows an empty-looking chip",
where:"guides/agent, 'Following the work' table",
what:"The chip holds only '…', which in Geist Mono is three dots on the baseline of a 16×22 chip. The rows around it use real placeholders (path, name).",
fix:"<code>command</code> instead of <code>…</code>.",
applied:true, shots:["ellipsis"]},
{id:"V23",sev:"low",title:"Shell blocks colour only the first env assignment",
where:"development (local mode), local-build",
what:"Shiki's bash grammar colours <code>=1</code> on the first assignment and leaves the rest plain, and the two <code>$(openssl …)</code> calls on one line come out in different colours.",
fix:"Not applied: write these as <code>export</code> lines, or accept it. Low value on its own.",
applied:false, shots:["bash"]}
];
